from unittest.mock import MagicMock, patch

import pytest
from langchain_core.documents import Document
from src.rag.groq_llm import GroqRagChain, run_groq_chat


def _fake_completion(text):
    completion = MagicMock()
    message = MagicMock()
    message.content = text
    choice = MagicMock()
    choice.message = message
    completion.choices = [choice]
    return completion


def test_run_groq_chat_returns_message_text():
    with patch("src.rag.groq_llm.Groq") as mock_groq:
        client = mock_groq.return_value
        client.chat.completions.create.return_value = _fake_completion("response text\n")

        result = run_groq_chat(
            "hello",
            model="llama-3.3-70b-versatile",
            api_key="test-key",
            temperature=0.2,
            timeout_seconds=5,
            max_tokens=100,
        )

    assert result == "response text"
    mock_groq.assert_called_once_with(api_key="test-key", timeout=5)
    client.chat.completions.create.assert_called_once_with(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": "hello"}],
        temperature=0.2,
        max_tokens=100,
    )


def test_run_groq_chat_requires_api_key(monkeypatch):
    monkeypatch.delenv("GROQ_API_KEY", raising=False)

    with pytest.raises(RuntimeError, match="GROQ_API_KEY"):
        run_groq_chat("hello", model="llama-3.3-70b-versatile", api_key=None)


def test_groq_rag_chain_invoke():
    mock_retriever = MagicMock()
    mock_retriever.invoke.return_value = [
        Document(page_content="Context document 1", metadata={"source": "doc1"}),
        Document(page_content="Context document 2", metadata={"source": "doc2"}),
    ]

    prompt_template = "Context:\n{context}\nQuestion: {question}"

    chain = GroqRagChain(
        retriever=mock_retriever,
        prompt_template=prompt_template,
        model="llama-3.3-70b-versatile",
        api_key="test-key",
        temperature=0.3,
        timeout_seconds=60,
        max_context_chars=5000,
        max_completion_tokens=500,
    )

    with patch("src.rag.groq_llm.run_groq_chat") as mock_chat:
        mock_chat.return_value = "Answer generated by Groq"

        result = chain.invoke({"query": "How to trade resin?"})

        assert result["result"] == "Answer generated by Groq"
        assert len(result["source_documents"]) == 2
        mock_chat.assert_called_once_with(
            prompt="Context:\nContext document 1\n\nContext document 2\nQuestion: How to trade resin?",
            model="llama-3.3-70b-versatile",
            api_key="test-key",
            temperature=0.3,
            timeout_seconds=60,
            max_tokens=500,
        )


def test_groq_rag_chain_empty_query():
    chain = GroqRagChain(
        retriever=MagicMock(),
        prompt_template="{context} {question}",
        model="llama-3.3-70b-versatile",
    )
    with pytest.raises(ValueError, match="Query is required"):
        chain.invoke({"query": "   "})


def test_groq_rag_chain_no_retriever():
    chain = GroqRagChain(
        retriever=None,
        prompt_template="{context} {question}",
        model="llama-3.3-70b-versatile",
    )
    with pytest.raises(RuntimeError, match="No retriever is available"):
        chain.invoke({"query": "Valid query"})


def test_groq_rag_chain_context_char_budget():
    mock_retriever = MagicMock()
    mock_retriever.invoke.return_value = [
        Document(page_content="Small text", metadata={}),
        Document(page_content="Extra long text that exceeds budget", metadata={}),
    ]

    chain = GroqRagChain(
        retriever=mock_retriever,
        prompt_template="Context: {context}\nQuestion: {question}",
        model="llama-3.3-70b-versatile",
        api_key="test-key",
        max_context_chars=15,  # Only first piece fits + separator
    )

    with patch("src.rag.groq_llm.run_groq_chat") as mock_chat:
        mock_chat.return_value = "Answer"
        res = chain.invoke({"query": "Test"})
        assert len(res["source_documents"]) == 1
        assert res["source_documents"][0].page_content == "Small text"
